<?php

use App\Models\Stock\Stock;
use App\Models\Stock\StockMake;
use App\Models\Stock\StockModel;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $data = [
            'volvo'         => [
                '960',
                'C30',
                'C70',
                'Ex30',
                'S40',
                'S60',
                'S80',
                'S90',
                'V40',
                'V50',
                'V60',
                'V70',
                'V90',
                'XC 90',
                'Xc40',
                'Xc60',
                'Xc70',
                'Xc90',
            ],
            'volkswagen'    => [
                'Arteon',
                'Beach',
                'Beetle',
                'CC',
                'Caddy',
                'Citi',
                'FOX',
                'Golf 3',
                'Golf 4',
                'Golf 5',
                'Golf 6',
                'Golf 7',
                'Golf 8',
                'Golf SV',
                'Jetta',
                'Jetta 1I',
                'Jetta 3',
                'Jetta 4',
                'Jetta 5',
                'Jetta 6',
                'Kombi AND Microbus',
                'Microbus Syncro / T4',
                'Passat',
                'Polo',
                'Polo Classic',
                'Polo Playa',
                'Polo Vivo',
                'Scirocco',
                'Sharan',
                'T-Cross',
                'T-ROC',
                'T5',
                'T6',
                'Taigo',
                'Tiguan',
                'Touareg',
                'Touran',
                'Transporter',
                'UP',

                'Amarok',
                'Golf Bakkies',
                'Transporter',
            ],
            'toyota'        => [
                '86',
                'Agya',
                'Auris',
                'Avanza',
                'Aygo',
                'C-HR',
                'Camry',
                'Condor',
                'Conquest',
                'Corolla',
                'Corolla Cross',
                'Corolla Quest',
                'Cressida',
                'Etios',
                'Fortuner',
                'GEN',
                'HI ACE',
                'Hilux',
                'Land Cruiser',
                'Land Cruiser 70 Series',
                'Prado',
                'Prius',
                'Quantum',
                'RAV 4',
                'Rumion',
                'Runx',
                'Rush',
                'Starlet',
                'Tazz',
                'Urban Cruiser',
                'Verso',
                'Vitz',
                'Yaris',

                'Corona',
                'Hilux',
                'Land Cruiser',
                'Stallion',
            ],
            'tata'          => [
                'indica',

                'Super ACE',
                'Xenon',
            ],
            'suzuki'        => [
                'Baleno',
                'Celerio',
                'Ciaz',
                'Eeco',
                'Ertiga',
                'Fronx',
                'Grand Vitara',
                'Ignis',
                'Jimny',
                'S-Presso',
                'SX4',
                'Splash',
                'Swift',
                'Vitara',
                'XL6',

                'Super Carry',
            ],
            'subaru'        => [
                'Forester',
                'Impreza',
                'Outback',
                'Tribeca',
                'XV',
            ],
            'ssangyong'     => [
                'Korando',
                'Kyron',
                'Rexton',

                'Actyon Sports',
            ],
            'smart'         => [
                'Coupe',
                'Forfour',
                'Smart Coupe',
            ],
            'secma'         => [
                'F16',
            ],
            'seat'          => [
                'Ibiza',
                'Leon',
            ],
            'renault'       => [
                'Captur',
                'Clio',
                'Clio III',
                'Clio IV',
                'Duster',
                'Fluence',
                'Kadjar',
                'Kiger',
                'Koleos',
                'Kwid',
                'Logan',
                'Megane',
                'Megane II',
                'Megane III',
                'Megane IV',
                'Modus',
                'Sandero',
                'Scenic',
                'Scenic II',
                'Trafic',
                'Triber',
            ],
            'proton'        => [
                'Persona',
                'Saga',
                'X50',
                'X70',
                'X90',
            ],
            'porsche'       => [
                '911',
                'Boxster',
                'Cayenne',
                'Cayenne Coupe',
                'Cayman',
                'Macan',
                'Panamera',
            ],
            'peugeot'       => [
                '107',
                '107 / 108',
                '2008',
                '207',
                '208',
                '3008',
                '307',
                '308',
                'Partner',
                'RCZ',

                'Landtrek',
            ],
            'opel'          => [
                'Adam',
                'Astra',
                'Combo',
                'Corsa',
                'Crossland',
                'Crossland X',
                'Grandland X',
                'Kadett',
                'Meriva',
                'Mokka',
                'Tigra',
                'Vivaro',
            ],
            'omoda'         => [
                'omoda',
            ],
            'nissan'        => [
                '350 Z',
                '350 Z/370 Z',
                '370 Z',
                'Almera',
                'Grand Livina',
                'Juke',
                'Laurel',
                'Livina',
                'Magnite',
                'Micra',
                'Murano',
                'Nv200',
                'Nv350',
                'Pathfinder',
                'Patrol',
                'Primera',
                'Qashqai',
                'Sani',
                'Sentra',
                'Tiida',
                'X Trail',

                'Hardbody',
                'NP200',
                'Navara',
                'Patrol',
            ],
            'mitsubishi'    => [
                'ASX',
                'Eclipse Cross',
                'Lancer',
                'Outlander',
                'Pajero',
                'Pajero Sport',
                'Xpander',

                'Colt',
                'Triton',
            ],
            'mini'          => [
                'Clubman',
                'Cooper',
                'Cooper 5 Door',
                'Cooper 5DR',
                'Cooper Clubman',
                'Cooper Convertible',
                'Cooper Countryman',
                'Cooper Paceman',
                'Cooper Roadster',
                'Mini ONE',
            ],
            'mercedes-benz' => [
                'A Class',
                'A Class Sedan',
                'B Class',
                'C Class',
                'C Class Coupe',
                'C Class Estate',
                'C Class Sedan',
                'CL Class',
                'CLA',
                'CLC Coupe',
                'CLK Class Cabriolet',
                'CLK Class Coupe',
                'CLS Class',
                'E Class',
                'E Class Cabriolet',
                'E Class Coupe',
                'E Class Sedan',
                'EQA',
                'EQC',
                'G Class',
                'GL Class',
                'GLA',
                'GLB',
                'GLC',
                'GLE',
                'M Class',
                'S Class',
                'SLC',
                'SLK Class',
                'V Class',
                'V250',
                'Viano',
                'Vito',
                'Vito BUS',
                'W107',
                'W115 Shape Sedan',
                'W124 Shape Sedan',

                'X-Class',
            ],
            'mazda'         => [
                '323',
                '626',
                'CX-3',
                'CX-30',
                'CX-5',
                'CX-60',
                'CX-7',
                'Etude',
                'Mazda 2',
                'Mazda 3',
                'Mazda 5',
                'Mazda 6',

                'B Series',
                'BT 50 Series',
                'Rustler',
            ],
            'maserati'      => [
                'Ghibli',
                'Quattroporte',
            ],
            'mahindra'      => [
                'KUV 100',
                'Scorpio',
                'Scorpio-N',
                'TUV',
                'Thar',
                'XUV',
                'Xuv300',
                'Xuv3xo',

                'Bolero',
                'PIK UP',
                'Scorpio',
            ],
            'mg'            => [
                'MG ZS',
                'MG6',
                'MGB',
                'MGF',
                'TF',
            ],
            'lotus'         => [
                '7',
            ],
            'leyland'       => [
                'Mini',

                'Dost',
            ],
            'lexus'         => [
                'ES',
                'GS',
                'IS',
                'LX',
                'NX',
                'RX',
                'UX',
            ],
            'land-rover'    => [
                'Defender 110',
                'Defender 130',
                'Defender 90',
                'Discovery',
                'Discovery Sport',
                'Evoque',
                'Freelander',
                'Range Rover',
                'Range Rover Sport',
                'Velar',

                '109',
                'Defender',
                'PUP 6',
            ],
            'ldv'           => [
                'T60',
            ],
            'kia'           => [
                'Carnival',
                'Cerato',
                'Grand Sedona',
                'Magentis',
                'Pegas',
                'Picanto',
                'RIO',
                'Sedona',
                'Seltos',
                'Sonet',
                'Sorento',
                'Soul',
                'Sportage',
                'Stinger',

                'K 2500',
                'K 2700',
            ],
            'jiayuan'       => [
                'Eidola',
            ],
            'jetour'        => [
                'Dashing',
                'X70',
            ],
            'jeep'          => [
                'Cherokee',
                'Compass',
                'Grand Cherokee',
                'Patriot',
                'Renegade',
                'Srt8',
                'Willys ',
                'Wrangler',

                'Gladiator',
            ],
            'jaguar'        => [
                'E-Pace',
                'F-Pace',
                'F-Type',
                'S-Type',
                'X-Type',
                'XE',
                'XF',
                'XJ',
                'XJ6',
                'XK',
            ],
            'jaecoo'        => [
                'J7',
            ],
            'jmc'           => [
                'BD',
            ],
            'jac'           => [
                'T6',
                'T8',
                'X200',
            ],
            'isuzu'         => [
                'MU-X',
                'Trooper',

                'D-MAX',
                'KB',
            ],
            'infiniti'      => [
                'EX',
                'FX/QX70',
                'G',
                'Q50',
            ],
            'ineos'         => [
                'Grenadier',
            ],
            'hyundai'       => [
                'Accent',
                'Atos/Atoz',
                'Creta',
                'Elantra',
                'Exter',
                'Getz',
                'Grand Creta',
                'H-1',
                'I30n',
                'Kona',
                'Santa-FE',
                'Sonata',
                'Staria',
                'Terracan',
                'Tucson',
                'Veloster',
                'Venue',
                'i10',
                'i20',
                'i30',
                'iX35',

                'H100',
            ],
            'hummer'        => [
                'H3',
            ],
            'honda'         => [
                'Accord',
                'Amaze',
                'BR-V',
                'Ballade',
                'Brio',
                'CRV',
                'Civic',
                'FIT',
                'HR-V',
                'Insight',
                'Jazz',
                'Prelude',
                'WR-V',
            ],
            'haval'         => [
                'H1',
                'H2',
                'H6',
                'H7',
                'H9',
                'Jolion',
            ],
            'geely'         => [
                'LC',
            ],
            'gwm'           => [
                'H5',
                'H6',
                'M4',
                'Tank 300',

                'LDV',
                'P Series',
                'P-Series',
                'Steed',
                'Steed 5',
            ],
            'foton'         => [
                'View',

                'Thunda',
                'Tunland',
            ],
            'ford'          => [
                'B-MAX',
                'Ecosport',
                'Escort',
                'Everest',
                'Explorer',
                'Fairmont',
                'Falcon',
                'Fiesta',
                'Figo',
                'Focus',
                'Fusion',
                'Ikon',
                'KA',
                'Kuga',
                'Laser',
                'Mondeo',
                'Mustang',
                'Sapphire',
                'Sierra',
                'Telstar',
                'Tourneo',
                'Tourneo Connect',
                'Transit',

                'Bantam',
                'Cortina Bakkie',
                'Ranger',
            ],
            'fiat'          => [
                '500',
                '500L',
                '500x',
                'Bravo',
                'Doblo',
                'Fiorino',
                'Grande Punto',
                'Linea',
                'Palio',
                'Panda',
                'Punto',
                'Qubo',
                'Siena',
                'Tipo',

                'Fullback',
                'Strada',
            ],
            'ferrari'       => [
                'Scuderia',
            ],
            'faw'           => [
                'V2',
            ],
            'dodge'         => [
                'Caliber',
                'Journey',
                'Nitro',
            ],
            'datsun'        => [
                'GO',
                'GO Plus',
            ],
            'daihatsu'      => [
                'Charade',
                'Cuore',
                'Gran Move',
                'Sirion',
                'Terios',

                'Gran MAX',
            ],
            'citroen'       => [
                'C1',
                'C2',
                'C3',
                'C4',
                'C5',
                'GS',
            ],
            'chrysler'      => [
                'Grand Voyager',
                'Neon',
                'PT Cruiser',
                'Sebring',
            ],
            'colt'          => [
                'Colt',
            ],
            'chevrolet'     => [
                'Aveo',
                'Captiva',
                'Cruze',
                'Elcamino',
                'Lumina',
                'Optra',
                'Orlando',
                'Sonic',
                'Spark',
                'Trailblazer',

                'C10',
                'Corsa Utility',
                'Utility',
            ],
            'chery'         => [
                'J1',
                'Omoda',
                'QQ3',
                'Tiggo',
                'Tiggo 4',
                'Tiggo 7',
                'Tiggo 8 PRO',
            ],
            'cadillac'      => [
                'BLS',
            ],
            'baic'          => [
                'B40',
                'X25',
                'X55',
            ],
            'bmw'           => [
                '1 Series',
                '1 Series (f40)',
                '2 Series',
                '2 Series Active Tour',
                '2 Series Gran Coupe',
                '3 Series',
                '3 Series GT',
                '4 Series',
                '4 Series Gran Coupe',
                '5 Series',
                '6 Series',
                '7 Series',
                '8 Series',
                'X1',
                'X2',
                'X3',
                'X4',
                'X5',
                'X6',
                'X7',
                'XM',
                'Z3',
                'Z4',
                'i3',
                'iX3',
            ],
            'audi'          => [
                '400',
                '500',
                'A1',
                'A3',
                'A3 Sportback',
                'A4',
                'A4 Allroad',
                'A5',
                'A6',
                'A7',
                'A8',
                'Q2',
                'Q3',
                'Q5',
                'Q7',
                'Q8',
                'RS3',
                'RS4',
                'RS5',
                'S3',
                'S4',
                'S5',
                'S6',
                'TT',
                'e-TRON',
            ],
            'aston-martin'  => [
                'DB9',
                'Db11',
                'Vantage',
            ],
            'alfa-romeo'    => [
                '147',
                '159',
                'Giulietta',
                'MiTO',
                'Stelvio',
            ],
            'abarth'        => [
                '124',
                '500/695',
            ],
        ];

        foreach ($data as $make => $models) {
            $record = StockMake::where('slug', $make)->firstOrFail();
            foreach ($models as $model) {
                $record->models()->firstOrCreate(
                    ['name' => $model],
                    ['name' => $model],
                );
            }

        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
